// Senarai zon JAKIM - kod zon rasmi e-Solat
const ZONES = [
  { code: "JHR01", state: "Johor", area: "Pulau Aur, Pemanggil" },
  { code: "JHR02", state: "Johor", area: "Kota Tinggi, Mersing, Johor Bahru" },
  { code: "JHR03", state: "Johor", area: "Kluang, Pontian" },
  { code: "JHR04", state: "Johor", area: "Batu Pahat, Muar, Segamat, Gemas Johor" },
  { code: "KDH01", state: "Kedah", area: "Kota Setar, Kubang Pasu, Pokok Sena" },
  { code: "KDH02", state: "Kedah", area: "Kuala Muda, Yan, Pendang" },
  { code: "KDH03", state: "Kedah", area: "Padang Terap, Sik" },
  { code: "KDH04", state: "Kedah", area: "Baling" },
  { code: "KDH05", state: "Kedah", area: "Bandar Baharu, Kulim" },
  { code: "KDH06", state: "Kedah", area: "Langkawi" },
  { code: "KDH07", state: "Kedah", area: "Puncak Gunung Jerai" },
  { code: "KTN01", state: "Kelantan", area: "Bachok, Kota Bharu, Machang, Pasir Mas, Pasir Puteh, Tanah Merah, Tumpat, Kuala Krai, Mukim Chiku" },
  { code: "KTN03", state: "Kelantan", area: "Gua Musang, Jeli, Kg Aring" },
  { code: "MLK01", state: "Melaka", area: "Seluruh Negeri Melaka" },
  { code: "NGS01", state: "Negeri Sembilan", area: "Tampin, Jempol" },
  { code: "NGS02", state: "Negeri Sembilan", area: "Jelebu, Kuala Pilah, Rembau" },
  { code: "NGS03", state: "Negeri Sembilan", area: "Port Dickson, Seremban" },
  { code: "PHG01", state: "Pahang", area: "Pulau Tioman" },
  { code: "PHG02", state: "Pahang", area: "Kuantan, Pekan, Rompin, Muadzam Shah" },
  { code: "PHG03", state: "Pahang", area: "Jerantut, Temerloh, Maran, Bera, Chenor, Jengka" },
  { code: "PHG04", state: "Pahang", area: "Bentong, Lipis, Raub" },
  { code: "PHG05", state: "Pahang", area: "Genting Sempah, Janda Baik, Bukit Tinggi" },
  { code: "PHG06", state: "Pahang", area: "Cameron Highlands, Genting Highlands, Bukit Fraser" },
  { code: "PLS01", state: "Perlis", area: "Kangar, Padang Besar, Arau" },
  { code: "PNG01", state: "Pulau Pinang", area: "Seluruh Negeri Pulau Pinang" },
  { code: "PRK01", state: "Perak", area: "Tapah, Slim River, Tanjung Malim" },
  { code: "PRK02", state: "Perak", area: "Kuala Kangsar, Sg. Siput, Ipoh, Batu Gajah, Kampar" },
  { code: "PRK03", state: "Perak", area: "Lenggong, Pengkalan Hulu, Grik" },
  { code: "PRK04", state: "Perak", area: "Temengor, Belum" },
  { code: "PRK05", state: "Perak", area: "Kg Gajah, Teluk Intan, Bagan Datuk, Seri Iskandar, Beruas, Parit, Lumut, Sitiawan, Pulau Pangkor" },
  { code: "PRK06", state: "Perak", area: "Selama, Taiping, Bagan Serai, Parit Buntar" },
  { code: "PRK07", state: "Perak", area: "Bukit Larut" },
  { code: "SBH01", state: "Sabah", area: "Sandakan, Bukit Garam, Semawang, Temanggong, Tambisan" },
  { code: "SBH02", state: "Sabah", area: "Beluran, Telupid, Pinangah, Terusan, Kuamut" },
  { code: "SBH03", state: "Sabah", area: "Lahad Datu, Silabukan, Kunak, Sahabat, Semporna, Tungku" },
  { code: "SBH04", state: "Sabah", area: "Bandar Tawau, Balong, Merotai, Kalabakan" },
  { code: "SBH05", state: "Sabah", area: "Kudat, Kota Marudu, Pitas, Pulau Banggi" },
  { code: "SBH06", state: "Sabah", area: "Gunung Kinabalu" },
  { code: "SBH07", state: "Sabah", area: "Kota Kinabalu, Ranau, Kota Belud, Tuaran, Penampang, Papar, Putatan" },
  { code: "SBH08", state: "Sabah", area: "Pensiangan, Keningau, Tambunan, Nabawan" },
  { code: "SBH09", state: "Sabah", area: "Beaufort, Kuala Penyu, Sipitang, Tenom, Long Pasia, Membakut, Weston" },
  { code: "SGR01", state: "Selangor", area: "Gombak, Petaling, Sepang, Hulu Langat, Hulu Selangor, Shah Alam" },
  { code: "SGR02", state: "Selangor", area: "Kuala Selangor, Sabak Bernam" },
  { code: "SGR03", state: "Selangor", area: "Klang, Kuala Langat" },
  { code: "SWK01", state: "Sarawak", area: "Limbang, Lawas, Sundar, Trusan" },
  { code: "SWK02", state: "Sarawak", area: "Miri, Niah, Bekenu, Sibuti, Marudi" },
  { code: "SWK03", state: "Sarawak", area: "Pandan, Belaga, Suai, Tatau, Sebauh, Bintulu" },
  { code: "SWK04", state: "Sarawak", area: "Sibu, Mukah, Dalat, Song, Igan, Oya, Balingian, Kanowit, Kapit" },
  { code: "SWK05", state: "Sarawak", area: "Sarikei, Matu, Julau, Rajang, Daro, Bintangor, Belawai" },
  { code: "SWK06", state: "Sarawak", area: "Lubok Antu, Sri Aman, Roban, Debak, Kabong, Lingga, Engkelili, Betong, Spaoh, Pusa, Saratok" },
  { code: "SWK07", state: "Sarawak", area: "Serian, Simunjan, Samarahan, Sebuyau, Meludam" },
  { code: "SWK08", state: "Sarawak", area: "Kuching, Bau, Lundu, Sematan" },
  { code: "SWK09", state: "Sarawak", area: "Zon Khas (Kampung Patarikan)" },
  { code: "TRG01", state: "Terengganu", area: "Kuala Terengganu, Marang, Kuala Nerus" },
  { code: "TRG02", state: "Terengganu", area: "Besut, Setiu" },
  { code: "TRG03", state: "Terengganu", area: "Hulu Terengganu" },
  { code: "TRG04", state: "Terengganu", area: "Dungun, Kemaman" },
  { code: "WLY01", state: "WP", area: "Kuala Lumpur, Putrajaya" },
  { code: "WLY02", state: "WP", area: "Labuan" }
];

if (typeof module !== 'undefined') module.exports = ZONES;
